config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
    }
  root "uho_quotes#top"
  get "categories", to: "uho_quotes#categories", as: "categories"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/categories/:category", to: "uho_quotes#show", as: :category_uho_quote
  get "quote/:uuid", to: "uho_quotes#show", as: "quote"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/uho_quotes_controller.rb
class UhoQuotesController < ApplicationController
  require "yaml"
  before_action :set_uho_quotes
  before_action :set_category_title, only: [ :categories, :show ]

  def top
    clean_old_ogps if rand < 0.05 # 5% の確率で掃除（負荷対策）
  end

  def categories; end

  def show
    if params[:uuid].present?
      load_quote_from_cache(params[:uuid])
    else
      category = params[:category]
      generate_new_quote(category)
    end

    image_url = "#{request.base_url}/ogps/#{@ogp_id}.png"
    prepare_meta_tags(image_url)
  end

  private

  def load_quote_from_cache(uuid)
    cached_data = Rails.cache.read(uuid)
    unless cached_data
      redirect_to root_path
      return
    end

    @selected_uho_quote = cached_data[:quote]
    @category_key = cached_data[:category]
    @category = I18n.exists?("uho_quotes.#{@category_key}") ? I18n.t("uho_quotes.#{@category_key}") : t("uho_quotes.title")
    @ogp_id = uuid
  end

  def set_category_title
    @category_title = @uho_quotes["category_title"]&.sample
  end

  def generate_new_quote(category)
    @selected_uho_quote = params[:quote] || @uho_quotes[category]&.sample
    @category = I18n.t("uho_quotes.#{category}", default: t("uho_quotes.title"))
    @category_key = category
    @ogp_id = SecureRandom.uuid

    ogp_dir = Rails.root.join("public", "ogps")

    # mkdir_p でpublic/ogps フォルダの存在確認＋再帰作成
    FileUtils.mkdir_p(ogp_dir)
    ogp_path = ogp_dir.join("#{@ogp_id}.png")

    # 指定されたUUIDに対応する.pngファイルがあるか確認
    unless File.exist?(ogp_path)
      OgpCreator.build(@selected_uho_quote, category).write(ogp_path)
    end

    # UUIDと名言データをキャッシュに保存
    Rails.cache.write(@ogp_id, { quote: @selected_uho_quote, category: category }, expires_in: 1.days)
    @category_key = category
    @category = I18n.exists?("uho_quotes.#{@category_key}") ? I18n.t("uho_quotes.#{@category_key}") : t("uho_quotes.title")
  end

  def set_uho_quotes
    @uho_quotes = YAML.load_file(Rails.root.join("config", "uho_quotes.yml"))
  end

  def prepare_meta_tags(image_url)
  # このimage_urlにMiniMagickで設定したOGPの生成した合成画像を代入する
  set_meta_tags og: {
                  site_name: "ウホ名言",
                  title: "ウホ名言",
                  description: @selected_uho_quote,
                  type: "website",
                  url: request.original_url,
                  image: image_url,
                  locale: "ja-JP"
                 },
                  twitter: {
                  card: "summary_large_image",
                  image: image_url
                }
  end

  def clean_old_ogps
    ogp_dir = Rails.root.join("public", "ogps")
    return unless Dir.exist?(ogp_dir)

    Dir.glob("#{ogp_dir}/*.png").each do |file|
      if File.mtime(file) < 1.days.ago
        begin
          Rails.logger.info "削除: #{file}" # 削除処理をログに出力
          File.delete(file)
        rescue => e
          Rails.logger.warn "削除失敗: #{file}"
        end
      end
    end
  end
end

app/helpers/uho_quotes_helper.rb
module UhoQuotesHelper
end

app/views/uho_quotes/categories.html.erb
<!-- 画面警告表示 -->
<div id="screen-warning" class="fixed inset-0 bg-uho-middle_gray text-uho-dark_gray 
         flex flex-col items-center justify-center text-center text-xl z-50 hidden">
  <div class="text-center mb-3">  
    画面を大きくしてみてね
  </div>
  <div>
    <%= image_tag 'uho_for_phone.svg' %>
  </div>
</div>

<div class="p-2 2xl:p-6">
  <div class="flex-col flex-grow items-stretch justify-center w-full ipad:flex">
    <div class="text-uho-dark_gray font-bold text-center p-2 md:p-6 2xl:p-10">
      <h2 class="text-3xl md:text-4xl 2xl:text-5xl">
        <%= @category_title %>を選んでね</h2>
    </div>
    <!-- sm時表示 -->
    <div class="block ipad:block md:hidden">
      <div class="flex items-center justify-center">
        <div>
          <%= image_tag 'uho_for_phone.svg' %>
        </div>
      </div>
      <div class="text-center mb-3">
        今はどんな気分かな？
      </div>
    </div>

    <div class="relative grid grid-cols-1 md:grid-cols-2 gap-5 md:gap-14 justify-items-center 
                text-center text-lg md:text-base 2xl:text-lg text-uho-dark_brown
                md:pt-12 opacity-100 md:opacity-0 md:animate-fade-in">
      <%= link_to category_uho_quote_path("uho_power"), data: { turbo: false },
          class: "category-card bg-uho-orange hover-animation" do %>
        <div class="category-content">
          <%= image_tag 'uho_power.svg', class: 'w-10 h-10 md:w-32 md:h-32' %>
            <span class="text-center">ウホパワーが欲しい</span>
        </div>  
      <% end %>
      <%= link_to category_uho_quote_path("uho_healing"), data: { turbo: false },
          class:"category-card bg-uho-blue hover-animation" do %>
        <div class="category-content">
          <%= image_tag 'healing.svg', class: 'w-10 h-10 md:w-32 md:h-32' %>
            <span class="text-center">ウホヒーリングが欲しい</span>
        </div>
      <% end %>
      <%= link_to category_uho_quote_path("uho_love"), data: { turbo: false },
        class:"category-card bg-uho-red hover-animation" do %>
        <div class="category-content">
          <%= image_tag 'love.svg', class: 'w-10 h-10 md:w-32 md:h-32' %>
            <span class="text-center">ウホ愛に包まれたい</span>
        </div>
      <% end %>
      <%= link_to category_uho_quote_path("uho_yell"), data: { turbo: false },
        class:"category-card bg-uho-purple hover-animation" do %>
        <div class="category-content">
          <%= image_tag 'yell.svg', class: 'w-10 h-10 md:w-32 md:h-32' %>
           <span class="text-center">ウホエールが欲しい</span>
        </div>
      <% end %>
    </div>

    <!-- md時表示 -->
    <div class="flex items-center justify-center text-center 2xl:text-xl">
      <div class="hidden md:block ipad:hidden absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2">
                  今はどんな気分かな？
        <div class="transition-transform duration-300 ease-in-out hover:rotate-6 pt-3 ">
          <%= image_tag 'uho.svg' %>
        </div>
      </div>
    </div>
   </div>
  </div>
</div>

app/views/uho_quotes/show.html.erb
<div class="p-2 2xl:p-6">
  <div class="flex flex-col flex-grow items-center justify-center w-full">
    <div class="text-uho-dark_gray font-bold text-center pt-0 ipad:pt-6">
      <div class="text-3xl md:text-4xl"><%= @category %>が欲しい</div>
    </div>
    <div class="text-uho-dark_gray font-bold text-center">
      <div class="text-4xl md:text-5xl">あなたへ送る</div>
      <div class="text-4xl md:text-5xl md:my-2"><%= t('uho_quotes.title') %></div>
    </div>

    <div class="flex justify-center">
      <%= image_tag 'uho_for_phone.svg', class: 'w-24 h-24 md:hover:animate-guragura transition-transform' %>
    </div>

    <div class="pt-5 md:pt-10 2xl:pt-14 opacity-100 md:opacity-0 md:animate-fade-in">
      <div class="ring-2 ring-uho-brown rounded-3xl bg-uho-white px-4 py-10 md:p-9 text-center text-2xl md:text-4xl max-w-4xl w-auto mx-auto">
        <%= @selected_uho_quote %>
      </div>
    </div>

    <div class="p-4">
      <div class="flex justify-center items-center pt-3 md:pt-5 2xl:pt-12 gap-5">
        <%= link_to "https://twitter.com/intent/tweet?url=#{quote_url(uuid: @ogp_id)}&text=#{CGI.escape("ウホ名言で「#{@category}」をもらったよ！")}\n&hashtags=#{CGI.escape("ウホ名言")}", target: "_blank", 
             class: "ring-2 ring-uho-brown rounded-full bg-uho-dark_yellow px-5 py-5 text-black hover-animation" do %>
          <%= image_tag 'x.svg', class: 'mx-auto' %>
            でシェア
          <% end %>
          <div class="flex justify-center items-center mt-12">
            <%= link_to root_path, class: "ring-2 ring-uho-brown rounded-full bg-uho-blue px-5 py-5 hover-animation" do%>
              <%= image_tag 'house.svg', class: 'mx-auto' %>
            <% end %>
          </div>
        </div>
        <div class="flex justify-center items-center pt-2 md:pt-4 2xl:pt-6 gap-5 text-center">
          <%= link_to raw("#{@category_title}を<br>選び直す"), categories_path,
              class: "ring-2 ring-uho-brown rounded-full bg-uho-green px-5 py-5 text-black hover-animation"%>
        </div>
     </div>
    </div>
  </div>
</div>

app/views/uho_quotes/top.html.erb
<div class="p-2 2xl:p-6">
  <div class="flex flex-col flex-grow items-center w-full pt-2 md:pt-4 2xl:pt-10">
    <h1 class="text-6xl md:text-7xl text-uho-dark_gray font-bold"><%= t('uho_quotes.title') %></h1>

    <div class="opacity-100 md:opacity-0 md:animate-fade-in">
      <div class="pt-32 md:pt-36">
        <div>
         <%= image_tag 'uho.svg', class: "animate-yurayura transition-transform md:hover:pause" %>
        </div>
      </div>
    </div>

    <div class="pt-16 md:pt-24 2xl:pt-32 pb-6">
      <div class="text-center">
        <%= link_to "カテゴリを選ぶ", categories_path,
            class: "block ring-2 ring-uho-brown rounded-full bg-uho-middle_yellow px-6 py-6 text-black hover-animation"%>
      </div> 
    </div>
  </div>
</div>